# Test against this version of Node.js
environment:
  nodejs_version: "8"

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of node
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - npm i

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node -v
  - npm -v
  # run tests
  - npm test

# Don't actually build.
build: off
